# Default values for sts-task.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: namespace5oct
replicaCount: 1

image:
  repository: petrumariuta/stateful:latest
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
configMapName:
ingress:
  host: namespace5oct.local
  backendService: sts-task-namespace5oct
  backendPort: 80

volumeMounts:
  - name: pv-5oct
    mountPath: /test/tester1
volumes:
  - name: pv-5oct
  

