apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-5oct
  namespace: 5oct
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /test/tester
#  persistentVolumeReclaimPolicy: Recycle

