apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-5oct
  namespace: 5oct
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
